version: "3.8"

services:
  whisper-webui:
    build: .
    container_name: whisper-webui
    restart: unless-stopped
    ports:
      - "7860:7860"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whisper-ui.rule=Host(`whisper-ui.teastymenu.ru`)"
      - "traefik.http.routers.whisper-ui.entrypoints=websecure"
      - "traefik.http.routers.whisper-ui.tls=true"
      - "traefik.http.routers.whisper-ui.tls.certresolver=myresolver"
      - "traefik.http.services.whisper-ui.loadbalancer.server.port=7860"
    networks:
      - traefik

networks:
  traefik:
    external: true
